[theme]
base = "dark"
primaryColor = "#ffffff"
backgroundColor = "#000000"
secondaryBackgroundColor = "#121214"
textColor = "#ededed"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
